// build_l0.js — mechanical generator for policy_unified.js (EXACT-NN L0).
//
// T1 ("exact by construction") demands provenance, not trust: per the #6 spec
// revision, L0 must be VERBATIM REUSE of the prod policy sources, because prod
// is full of load-bearing quirks a rewrite silently breaks (two-pass
// accumulateFlock, the no-tie-break candidates() sort, the NaN paths, LIFO
// grid insertion, strict-> argmax...). So the artifact is GENERATED: this
// script concatenates the three policy sources BYTE-FOR-BYTE inside a shadow
// scope and adds a ~30-line non-arithmetic wrapper. Anyone can re-run the
// build and byte-compare:
//
//   node dev/exact_nn/build_l0.js            # (re)generate policy_unified.js
//   node dev/exact_nn/build_l0.js --check    # verify artifact == build (exit 1 if not)
//
// How the wrapper achieves "one module, one entry point" with ZERO edits to
// the embedded bytes:
//   * `var module;` + `var window = {};` shadow the embedded files' export
//     surfaces. cheap_planner.js / predator.js module guards see typeof
//     module === 'undefined' and skip; predator_cheap.js's IIFE publishes
//     window.__cheap / window.__predatorReady onto the SHADOW window, which
//     the wrapper captures. The real page globals are never touched — L0 can
//     load alongside prod without interfering.
//   * prod's own force() IS the single entry point: it already dispatches
//     N==0 -> Vector(0,0), N<=5 -> intercept, N>5 -> plan/steer. The wrapper
//     exposes that closure function DIRECTLY (no indirection, no arithmetic).
//   * The net loads through the embedded fetch chain exactly as prod does
//     (browser: real fetch; harness: the stub) -> identical JSON.parse.
//     Consumers await `ready`.
//   * Even the value-net viz forward (cp_value_viz after the argmax) runs
//     identically — its writes land in the embedded closure's private
//     vizModel, invisible outside. Equivalence is defined on returned force.
//   * PREDATOR_MAX_SPEED/FORCE/SIZE and EVOLVED_PATROL come from the embedded
//     predator.js bytes (wrapper-locals). Remaining sim-interface globals
//     (Vector, simNow, MAX_SPEED/MAX_FORCE/NEIGHBOR_DISTANCE/
//     DESIRED_SEPARATION/EPSILON/BORDER_OFFSET/PREDATOR_RANGE/
//     PREDATOR_TURN_FACTOR) resolve lexically outward to the page's own
//     boid.js/vector.js/rng.js — the same globals prod's files read, at the
//     same binding times. L0 must load after them, like predator_cheap.js.
//   * Strict-mode note: the wrapper is strict, so the embedded predator.js
//     (sloppy in prod) executes as strict code. Strict mode changes binding/
//     error semantics, never float arithmetic; predator.js assigns only
//     declared names (verified). Documented for completeness.
//
// opts.transform(filename, code) -> code' is available for HARNESS-ONLY
// in-memory builds (e.g. the __cheapDebug state hook applied to the embedded
// predator_cheap bytes, mirroring the hook applied to the reference). The
// committed artifact is ALWAYS the pristine build (--check enforces).
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SOURCES = ['cheap_planner.js', 'predator.js', 'predator_cheap.js'];

function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

function buildSource(srcDir, transform) {
    const parts = [];
    const hashes = {};
    for (const f of SOURCES) {
        let code = fs.readFileSync(path.join(srcDir, f), 'utf8');
        hashes[f] = sha256(code);
        if (transform) {
            const out = transform(f, code);
            if (out != null) code = out;
        }
        parts.push(
            '/* ===== BEGIN VERBATIM js/' + f + ' (sha256 ' + hashes[f] + ') ===== */\n' +
            code +
            '\n/* ===== END VERBATIM js/' + f + ' ===== */\n');
    }
    const header = [
        '// policy_unified.js — EXACT-NN L0: the unified-exact single predator policy.',
        '// AUTOGENERATED by dev/exact_nn/build_l0.js — DO NOT EDIT BY HAND.',
        '// Regenerate:  node dev/exact_nn/build_l0.js',
        '// Verify:      node dev/exact_nn/build_l0.js --check',
        '//',
        '// ONE module, ONE entry point (force) covering ALL N: N==0 -> Vector(0,0),',
        '// N<=5 -> torus intercept, N>5 -> NN-planner + steer — prod\'s own gate,',
        '// embedded byte-for-byte. The NN (value_net.json) is load-bearing in every',
        '// plan; it loads through the embedded fetch chain (await `ready`).',
        '//',
        '// Exactness tier: T1 — every operation influencing the returned force is',
        '// inside the VERBATIM byte ranges below, in prod\'s own order; the wrapper',
        '// contributes zero arithmetic. See build_l0.js for the full construction',
        '// rationale and the sim-interface dependency list (load after rng.js,',
        '// vector.js, boid.js).',
        '//',
        '// Embedded source attestations (prod = main@6dce76f):',
    ];
    for (const f of SOURCES) header.push('//   js/' + f + '  sha256 ' + hashes[f]);
    const body =
        header.join('\n') + '\n' +
        "'use strict';\n" +
        '(function (REALWIN, REALMODULE) {\n' +
        '    var captured = (function () {\n' +
        '        var module;          // contains embedded module.exports guards\n' +
        '        var window = {};     // capture surface for the embedded IIFE\n' +
        parts.join('') +
        '        return window;       // -> {__cheap, __predatorReady, __predatorModel}\n' +
        '    })();\n' +
        '    var api = {\n' +
        '        force: captured.__cheap.force,   // THE prod closure, no indirection\n' +
        '        ready: captured.__predatorReady, // resolves when the net is parsed\n' +
        '        _inner: captured,                // harness debug surface (transform builds)\n' +
        '    };\n' +
        '    if (REALMODULE) REALMODULE.exports = api;\n' +
        '    if (REALWIN) REALWIN.__exactnn = api;\n' +
        '})(typeof window !== \'undefined\' ? window : null,\n' +
        '   typeof module !== \'undefined\' ? module : null);\n';
    return { source: body, hashes };
}

function main() {
    const srcDir = path.join(__dirname, '..', '..', 'js');
    const outPath = path.join(__dirname, 'policy_unified.js');
    const { source, hashes } = buildSource(srcDir, null);
    if (process.argv.includes('--check')) {
        const onDisk = fs.readFileSync(outPath, 'utf8');
        if (onDisk === source) {
            console.log('OK: policy_unified.js is the pristine mechanical build of', SOURCES.join(', '));
            for (const f of SOURCES) console.log('   ', f, hashes[f]);
            process.exit(0);
        }
        console.error('MISMATCH: policy_unified.js differs from the mechanical build — regenerate it');
        process.exit(1);
    }
    fs.writeFileSync(outPath, source);
    console.log('wrote', outPath, source.length, 'bytes');
    for (const f of SOURCES) console.log('   embedded', f, 'sha256', hashes[f]);
}

if (require.main === module) main();
module.exports = { buildSource, SOURCES };
