// policy_unified.js — EXACT-NN L0: the unified-exact single predator policy.
// AUTOGENERATED by dev/exact_nn/build_l0.js — DO NOT EDIT BY HAND.
// Regenerate:  node dev/exact_nn/build_l0.js
// Verify:      node dev/exact_nn/build_l0.js --check
//
// ONE module, ONE entry point (force) covering ALL N: N==0 -> Vector(0,0),
// N<=5 -> torus intercept, N>5 -> NN-planner + steer — prod's own gate,
// embedded byte-for-byte. The NN (value_net.json) is load-bearing in every
// plan; it loads through the embedded fetch chain (await `ready`).
//
// Exactness tier: T1 — every operation influencing the returned force is
// inside the VERBATIM byte ranges below, in prod's own order; the wrapper
// contributes zero arithmetic. See build_l0.js for the full construction
// rationale and the sim-interface dependency list (load after rng.js,
// vector.js, boid.js).
//
// Embedded source attestations (prod = main@6dce76f):
//   js/cheap_planner.js  sha256 ed26e8f1d8ebcb2d4d9068dc955c59448ba293d7a60866e322dfd31d36a5ee74
//   js/predator.js  sha256 92a4efd3c5e66093b45f759f43f0a979bcc9fe25b1125d80fb7e898a76acb885
//   js/predator_cheap.js  sha256 a706d6640bdfbde3a0a614471210b34c7f420aa79b083a00a4b7204482ee5421
'use strict';
(function (REALWIN, REALMODULE) {
    var captured = (function () {
        var module;          // contains embedded module.exports guards
        var window = {};     // capture surface for the embedded IIFE
/* ===== BEGIN VERBATIM js/cheap_planner.js (sha256 ed26e8f1d8ebcb2d4d9068dc955c59448ba293d7a60866e322dfd31d36a5ee74) ===== */
// Cheap ballistic deploy policy — browser port of feat_planner.run_value_lookahead_cheap
// (prune_by='ball', K_roll=1). Pure functions so the same code runs under Node
// (parity test vs dev/js_fixture.json) and in predator_cheap.js.
//
// Decision (every D frames): generate 16 candidates (cand0=E3D patrol, cand1..15
// = nearest boids lead-adjusted); compute 19 pursuit features + 4 ctx per
// candidate; the tiny value net gives a prior V; pick the single most
// ballistically-catchable candidate, roll ONLY it Hs frames, score it
// (rollout catches + terminal value bootstrap); the other 15 keep their prior V;
// argmax -> commit. Ballistic selection makes 1 rollout ~= the full 16-rollout
// planner (sim_torch: 14.97 vs 15.23 ceiling).
'use strict';

// ---- constants (mirror feat_planner.py / sim_torch) ----
var CP_PS = 200.0, CP_VS = 6.0, CP_RHO = 70.0, CP_HB = 90;
var CP_INIT_N = 120;                 // initial boid count (for frac_alive)

// erf via Abramowitz & Stegun 7.1.26 (|err| < 1.5e-7) -> exact-GELU parity.
function cp_erf(x) {
    var s = x < 0 ? -1 : 1; x = Math.abs(x);
    var t = 1 / (1 + 0.3275911 * x);
    var y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x);
    return s * y;
}
function cp_gelu(x) { return 0.5 * x * (1 + cp_erf(x / Math.SQRT2)); }

// 2-body pursuit: predator (max-speed seek, no flock) vs constant-velocity boid.
// Returns {tCatchNorm, minDist, caught}. Mirrors _ballistic_intercept.
function cp_ballistic(px, py, vx, vy, bx, by, bvx, bvy, catchD, pmaxS, pmaxF, Hb) {
    Hb = Hb || CP_HB;
    var caught = false, tCatch = Hb, mind = Infinity;
    for (var t = 0; t < Hb; t++) {
        var dx = bx - px, dy = by - py;
        var d = Math.sqrt(dx * dx + dy * dy); if (d < 1e-6) d = 1e-6;
        if (d < mind) mind = d;
        if (!caught && d < catchD) { caught = true; tCatch = t; }
        var desx = dx / d * pmaxS - vx, desy = dy / d * pmaxS - vy;
        var sm = Math.sqrt(desx * desx + desy * desy); if (sm < 1e-6) sm = 1e-6;
        var sc = pmaxF / sm; if (sc > 1) sc = 1;
        vx += desx * sc; vy += desy * sc;
        var spd = Math.sqrt(vx * vx + vy * vy); if (spd < 1e-6) spd = 1e-6;
        var vsc = pmaxS / spd; if (vsc > 1) vsc = 1;
        vx *= vsc; vy *= vsc;
        px += vx; py += vy;
        bx += bvx; by += bvy;
    }
    return { tCatchNorm: tCatch / Hb, minDist: mind, caught: caught ? 1.0 : 0.0 };
}

// Per-candidate 19 features + shared 4 ctx, from a flat state.
// state: {px,py,pvx,pvy,psize, bx[],by[],bvx[],bvy[], nAlive}; cands: [{x,y}..](16)
// pmaxS/pmaxF: predator max speed/force. Returns {feat:[K][19], ctx:[4]}.
function cp_features(state, cands, pmaxS, pmaxF) {
    var px = state.px, py = state.py, pvx = state.pvx, pvy = state.pvy;
    var bx = state.bx, by = state.by, bvx = state.bvx, bvy = state.bvy;
    var n = bx.length, K = cands.length;
    var catchD = state.psize * 0.7;
    var feat = new Array(K);
    for (var k = 0; k < K; k++) {
        var cx = cands[k].x, cy = cands[k].y;
        var rx = cx - px, ry = cy - py;
        var dist = Math.sqrt(rx * rx + ry * ry); if (dist < 1e-6) dist = 1e-6;
        var tgo = dist / pmaxS;
        var isE3d = k === 0 ? 1.0 : 0.0;
        // nearest alive boid to the candidate point + local density / mean vel
        var best = Infinity, nb = 0, dens = 0, mvx = 0, mvy = 0, nNear = 0;
        var rho2 = CP_RHO * CP_RHO;
        for (var i = 0; i < n; i++) {
            var ddx = cx - bx[i], ddy = cy - by[i];
            var c2 = ddx * ddx + ddy * ddy;
            if (c2 < best) { best = c2; nb = i; }
            if (c2 < rho2) { dens++; mvx += bvx[i]; mvy += bvy[i]; nNear++; }
        }
        var tbDistCand = Math.sqrt(best < 0 ? 0 : best);
        var tbx = bx[nb], tby = by[nb], tbvx = bvx[nb], tbvy = bvy[nb];
        var tbrx = tbx - px, tbry = tby - py;
        var rangepb = Math.sqrt(tbrx * tbrx + tbry * tbry); if (rangepb < 1e-6) rangepb = 1e-6;
        var relvx = tbvx - pvx, relvy = tbvy - pvy;
        var closing = -(tbrx * relvx + tbry * relvy) / rangepb;
        var losRate = (tbrx * relvy - tbry * relvx) / (rangepb * rangepb);
        var nsafe = nNear > 0 ? nNear : 1.0;
        var mnx = mvx / nsafe, mny = mvy / nsafe;
        var ux = rx / dist, uy = ry / dist;
        var fleeAlign = mnx * ux + mny * uy;
        var b = cp_ballistic(px, py, pvx, pvy, tbx, tby, tbvx, tbvy, catchD, pmaxS, pmaxF, CP_HB);
        feat[k] = [
            rx / CP_PS, ry / CP_PS, dist / CP_PS, isE3d,
            tgo / 60.0,
            tbrx / CP_PS, tbry / CP_PS, tbvx / CP_VS, tbvy / CP_VS,
            tbDistCand / CP_PS,
            rangepb / CP_PS, closing / CP_VS, losRate * 50.0,
            dens / 20.0, fleeAlign / CP_VS,
            (rangepb - dist) / CP_PS,
            b.tCatchNorm, b.minDist / CP_PS, b.caught,
        ];
    }
    var fracAlive = state.nAlive / CP_INIT_N;
    var ctx = [pvx / CP_VS, pvy / CP_VS, fracAlive, state.psize / 20.0];
    return { feat: feat, ctx: ctx };
}

// Value net forward: standardize, 23->48->48->1 with GELU. net = value_net.json.
// Returns V[K].
function cp_value(net, feat, ctx) {
    var K = feat.length, V = new Array(K);
    var L0 = net.layers[0], L1 = net.layers[1], L2 = net.layers[2];
    var cs = [(ctx[0] - net.xmu[0]) / net.xsd[0], (ctx[1] - net.xmu[1]) / net.xsd[1],
              (ctx[2] - net.xmu[2]) / net.xsd[2], (ctx[3] - net.xmu[3]) / net.xsd[3]];
    for (var k = 0; k < K; k++) {
        var x = new Array(23);
        for (var i = 0; i < 19; i++) x[i] = (feat[k][i] - net.fmu[i]) / net.fsd[i];
        x[19] = cs[0]; x[20] = cs[1]; x[21] = cs[2]; x[22] = cs[3];
        var h0 = new Array(48);
        for (var j = 0; j < 48; j++) { var a = L0.b[j], wr = L0.w[j]; for (var q = 0; q < 23; q++) a += wr[q] * x[q]; h0[j] = cp_gelu(a); }
        var h1 = new Array(48);
        for (j = 0; j < 48; j++) { a = L1.b[j]; wr = L1.w[j]; for (q = 0; q < 48; q++) a += wr[q] * h0[q]; h1[j] = cp_gelu(a); }
        var o = L2.b[0], w2 = L2.w[0]; for (j = 0; j < 48; j++) o += w2[j] * h1[j];
        V[k] = o;
    }
    return V;
}

// ballistic pscore = caught - tCatchNorm  (feat[18] - feat[16]); argmax = top1.
function cp_top1(feat) {
    var best = -Infinity, bi = 0;
    for (var k = 0; k < feat.length; k++) {
        var ps = feat[k][18] - feat[k][16];
        if (ps > best) { best = ps; bi = k; }
    }
    return bi;
}

// --- "predator's brain" visualization adapter ---------------------------------
// Builds a model object matching activation_viz.js's interface (featureDim,
// layers[].{outDim, W, lastA}, lastNormalizedInput) from value_net.json, so the
// existing viz renders the cheap policy's value-net MLP unchanged. The viz reads
// W in-major (W[i*outDim+j] = weight prev-neuron i -> next-neuron j); value_net
// stores w[j][i] (out-major), so transpose once here.
function cp_viz_model(net) {
    var layers = [];
    for (var l = 0; l < net.layers.length; l++) {
        var L = net.layers[l], outDim = L.b.length, inDim = L.w[0].length;
        var W = new Float64Array(inDim * outDim);
        for (var j = 0; j < outDim; j++) for (var i = 0; i < inDim; i++) W[i * outDim + j] = L.w[j][i];
        layers.push({ outDim: outDim, W: W, lastA: new Float64Array(outDim) });
    }
    return { featureDim: net.fc + net.fctx, layers: layers,
        lastNormalizedInput: new Float64Array(net.fc + net.fctx) };
}

// Forward one candidate's (featRow, ctx) through the value net, recording the
// standardized input + per-layer activations into vizModel for activation_viz.js.
// Same math as cp_value (GELU hidden, linear output); used only for the chosen
// candidate each plan, so the brain viz shows the predator's committed decision.
function cp_value_viz(net, featRow, ctx, vizModel) {
    var x = vizModel.lastNormalizedInput, nf = net.fc;
    for (var i = 0; i < nf; i++) x[i] = (featRow[i] - net.fmu[i]) / net.fsd[i];
    for (i = 0; i < net.fctx; i++) x[nf + i] = (ctx[i] - net.xmu[i]) / net.xsd[i];
    var inp = x, last = net.layers.length - 1;
    for (var l = 0; l < net.layers.length; l++) {
        var L = net.layers[l], outDim = L.b.length, a = vizModel.layers[l].lastA;
        for (var j = 0; j < outDim; j++) {
            var s = L.b[j], wr = L.w[j];
            for (var q = 0; q < inp.length; q++) s += wr[q] * inp[q];
            a[j] = (l < last) ? cp_gelu(s) : s;
        }
        inp = a;
    }
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { cp_features: cp_features, cp_value: cp_value, cp_ballistic: cp_ballistic,
        cp_top1: cp_top1, cp_gelu: cp_gelu, cp_erf: cp_erf, cp_viz_model: cp_viz_model,
        cp_value_viz: cp_value_viz, CP: { PS: CP_PS, VS: CP_VS, RHO: CP_RHO, HB: CP_HB } };
}

/* ===== END VERBATIM js/cheap_planner.js ===== */
/* ===== BEGIN VERBATIM js/predator.js (sha256 92a4efd3c5e66093b45f759f43f0a979bcc9fe25b1125d80fb7e898a76acb885) ===== */
// Predator settings optimized for subtle background presence
var PREDATOR_MAX_SPEED = 2.5;
var PREDATOR_MAX_FORCE = 0.05;
var PREDATOR_SIZE = 12;

// Evolved patrol-target params (the deployed policy). Found by GPU-batched
// evolutionary search (CEM over the sim_torch 'evolved' target, AlphaEvolve
// flavor) — beats the previous nearest_cluster patrol by ~+0.52 catches/eval
// (8.38 vs 7.86, 2048 fresh seeds, ~4 SE) on the GPU sim. See
// dev/reports/evolve_patrol_results.md and dev/sim_torch.py 'evolved' branch
// (this JS is a line-for-line port of that computation).
var EVOLVED_PATROL = {
    cluster_r: 178.09,   // neighbor radius for the density count
    dens_pow: 2.373,     // exponent on (neighbors+1) — how much density attracts
    reach_scale: 1515.0, // exp(-distPred/reach_scale) — slow predator prefers near
    sharp: 9.25,         // peakiness of the softmax-like weighting (->densest boid)
    lead_scale: 0.454,   // adaptive travel-time lead gain
    lead_max: 230.6,     // cap on lead distance
    nbhd: 0.461,         // blend toward the densest boid's neighborhood centroid
    momentum: 0.0        // frame-to-frame target smoothing (0 = off)
};

// Patrol target = the evolved heuristic. For each live boid, attractiveness =
// (localNeighbors+1)^dens_pow * exp(-distToPredator/reach_scale); normalize to
// the per-frame max and raise to `sharp` to get soft weights, then take the
// weighted centroid + mean velocity, blend in the densest boid's neighborhood
// centroid (nbhd), and lead forward by the predator's travel time (capped).
// Mirrors sim_torch's 'evolved' _update_auto_target exactly.
function computeEvolvedTarget(predPos, boids, opt, prevTarget) {
    var n = boids.length;
    if (n === 0) return null;
    var R2 = opt.cluster_r * opt.cluster_r;
    var px = predPos.x, py = predPos.y;
    var attract = new Array(n);
    var amax = 1e-12, bestIdx = 0, bestA = -1;
    for (var i = 0; i < n; i++) {
        var bxi = boids[i].position.x, byi = boids[i].position.y;
        var cnt = 0; // neighbors within cluster_r (includes self)
        for (var j = 0; j < n; j++) {
            var ex = boids[j].position.x - bxi, ey = boids[j].position.y - byi;
            if (ex * ex + ey * ey < R2) cnt++;
        }
        var ddx = bxi - px, ddy = byi - py;
        var dpred = Math.sqrt(ddx * ddx + ddy * ddy);
        var a = Math.pow(cnt + 1, opt.dens_pow) * Math.exp(-dpred / opt.reach_scale);
        attract[i] = a;
        if (a > amax) amax = a;
        if (a > bestA) { bestA = a; bestIdx = i; }
    }
    var wsum = 0, cx0 = 0, cy0 = 0, vx0 = 0, vy0 = 0;
    for (var k = 0; k < n; k++) {
        var w = Math.pow(attract[k] / amax, opt.sharp);
        wsum += w;
        cx0 += w * boids[k].position.x; cy0 += w * boids[k].position.y;
        vx0 += w * boids[k].velocity.x; vy0 += w * boids[k].velocity.y;
    }
    if (wsum < 1e-12) wsum = 1e-12;
    cx0 /= wsum; cy0 /= wsum; vx0 /= wsum; vy0 /= wsum;
    var nbhd = opt.nbhd || 0;
    if (nbhd > 0) {
        var bx = boids[bestIdx].position.x, by = boids[bestIdx].position.y;
        var nsum = 0, ncx = 0, ncy = 0, nvx = 0, nvy = 0;
        for (var m = 0; m < n; m++) {
            var gx = boids[m].position.x - bx, gy = boids[m].position.y - by;
            if (gx * gx + gy * gy < R2) {
                ncx += boids[m].position.x; ncy += boids[m].position.y;
                nvx += boids[m].velocity.x; nvy += boids[m].velocity.y; nsum++;
            }
        }
        if (nsum < 1e-12) nsum = 1e-12;
        ncx /= nsum; ncy /= nsum; nvx /= nsum; nvy /= nsum;
        cx0 = (1 - nbhd) * cx0 + nbhd * ncx;
        cy0 = (1 - nbhd) * cy0 + nbhd * ncy;
        vx0 = (1 - nbhd) * vx0 + nbhd * nvx;
        vy0 = (1 - nbhd) * vy0 + nbhd * nvy;
    }
    var dx2 = cx0 - px, dy2 = cy0 - py;
    var dcent = Math.sqrt(dx2 * dx2 + dy2 * dy2);
    var lead = dcent / PREDATOR_MAX_SPEED * opt.lead_scale;
    if (lead < 0) lead = 0;
    if (lead > opt.lead_max) lead = opt.lead_max;
    var tx = cx0 + lead * vx0, ty = cy0 + lead * vy0;
    var mom = opt.momentum || 0;
    if (mom > 0 && prevTarget) {
        tx = mom * prevTarget.x + (1 - mom) * tx;
        ty = mom * prevTarget.y + (1 - mom) * ty;
    }
    return { x: tx, y: ty };
}
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { computeEvolvedTarget: computeEvolvedTarget, EVOLVED_PATROL: EVOLVED_PATROL };
}

// --- catch test: do the predator's and a boid's drawn triangles overlap? ------
// Both are arrowheads built exactly as render() does: tip = center +
// heading*forward, base corners = center +/- perpendicular*half. The predator's
// forward/half grow with its (feeding) size; a boid uses render_size. Overlap is
// exact via the separating-axis theorem, with a cheap circle reject first. A
// touch counts as a catch; any gap does not.
function catchTriangle(cx, cy, vx, vy, fwd, half) {
    var m = Math.sqrt(vx * vx + vy * vy) || 1, ux = vx / m, uy = vy / m;
    return [cx + ux * fwd, cy + uy * fwd, cx - uy * half, cy + ux * half, cx + uy * half, cy - ux * half];
}
function catchAxisSeparates(A, C) {            // is any edge-normal of A a separating axis?
    for (var i = 0; i < 6; i += 2) {
        var nx = A[i + 1] - A[(i + 3) % 6], ny = A[(i + 2) % 6] - A[i];
        var a0 = Infinity, a1 = -Infinity, c0 = Infinity, c1 = -Infinity, d;
        for (var j = 0; j < 6; j += 2) { d = A[j] * nx + A[j + 1] * ny; if (d < a0) a0 = d; if (d > a1) a1 = d; }
        for (var k = 0; k < 6; k += 2) { d = C[k] * nx + C[k + 1] * ny; if (d < c0) c0 = d; if (d > c1) c1 = d; }
        if (a1 < c0 || c1 < a0) return true;
    }
    return false;
}
function predatorCatchesBoid(px, py, pvx, pvy, psize, bx, by, bvx, bvy) {
    var reach = psize * 1.2 + render_size;     // farthest vertex from either center
    var dx = bx - px, dy = by - py;
    if (dx * dx + dy * dy > reach * reach) return false;
    var P = catchTriangle(px, py, pvx, pvy, psize * 1.2, psize * 0.3);
    var B = catchTriangle(bx, by, bvx, bvy, render_size, render_size / 3);
    return !catchAxisSeparates(P, B) && !catchAxisSeparates(B, P);
}

function Predator(x, y, simulation) {
    this.position = new Vector(x, y);
    this.velocity = new Vector(simRandom() * 2 - 1, simRandom() * 2 - 1); // Start with some velocity
    this.acceleration = new Vector(0, 0);
    this.simulation = simulation;
    this.autonomousTarget = new Vector(x, y);
    this.targetChangeTime = 0;
    this.targetChangeInterval = 5000; // Change target every 5 seconds for smoother, less erratic movement
    
    // Growth and feeding mechanics
    this.baseSize = PREDATOR_SIZE;
    this.currentSize = this.baseSize;
    this.maxSize = this.baseSize * 1.8; // Maximum growth
    this.growthPerFeed = 1.2; // How much to grow per boid eaten
    this.decayRate = 0.002; // How fast size decays back to normal
    this.lastFeedTime = 0;
    this.feedCooldown = 100; // Minimum time between feeding (ms)
}

Predator.prototype = {

    // The predator's policy: the cheap ballistic patrol (js/predator_cheap.js),
    // distilled from the receding-horizon planner teacher. Every few frames it
    // ballistically picks + rolls one candidate target; each frame it chases the
    // nearest boid within POLICY_R, else seeks that target. The page boot waits on
    // window.__predatorReady (the value-net load) before starting the sim, so
    // window.__cheap is always present here.
    getAutonomousForce: function(boids) {
        return window.__cheap.force(this, boids);
    },

    
    // Wrap-around boundary handling (similar to boids)
    bound: function() {
        var BORDER_OFFSET = 20;
        
        if (this.position.x > this.simulation.canvasWidth + BORDER_OFFSET) {
            this.position.x = -BORDER_OFFSET;
        }
        if (this.position.x < -BORDER_OFFSET) {
            this.position.x = this.simulation.canvasWidth + BORDER_OFFSET;
        }
        if (this.position.y > this.simulation.canvasHeight + BORDER_OFFSET) {
            this.position.y = -BORDER_OFFSET;
        }
        if (this.position.y < -BORDER_OFFSET) {
            this.position.y = this.simulation.canvasHeight + BORDER_OFFSET;
        }
    },
    
    // Check for boid collisions and handle feeding
    checkForPrey: function(boids) {
        var caughtBoids = [];
        for (var i = 0; i < boids.length; i++) {
            var b = boids[i];
            // Catch when the predator's drawn triangle overlaps the boid's.
            if (predatorCatchesBoid(this.position.x, this.position.y, this.velocity.x, this.velocity.y, this.currentSize,
                                    b.position.x, b.position.y, b.velocity.x, b.velocity.y)) {
                caughtBoids.push(i);
                this.feed();
                break; // Only catch one boid at a time for smooth animation
            }
        }
        return caughtBoids;
    },
    
    // Handle feeding - grow predator
    feed: function() {
        this.currentSize = Math.min(this.currentSize + this.growthPerFeed, this.maxSize);
        this.lastFeedTime = simNow();
    },
    
    // Gradually decay size back to normal
    decaySize: function() {
        if (this.currentSize > this.baseSize) {
            this.currentSize = Math.max(this.currentSize - this.decayRate, this.baseSize);
        }
    },

    update: function(boids) {
        // Reset acceleration
        this.acceleration.iMultiplyBy(0);
        
        // Apply autonomous steering force
        var autonomousForce = this.getAutonomousForce(boids);
        this.acceleration.iAdd(autonomousForce);
        
        // Update velocity and position
        this.velocity.iAdd(this.acceleration);
        this.velocity.iFastLimit(PREDATOR_MAX_SPEED);
        this.position.iAdd(this.velocity);
        
        // Handle boundaries
        this.bound();
    },
    
    render: function() {
        var ctx = this.simulation.ctx;
        
        // Draw predator as a distinctive but subtle elongated triangle (size scales with feeding)
        var directionVector = this.velocity.normalize().multiplyBy(this.currentSize * 1.2);
        var inverseVector1 = new Vector(-directionVector.y, directionVector.x);
        var inverseVector2 = new Vector(directionVector.y, -directionVector.x);
        inverseVector1 = inverseVector1.divideBy(4);
        inverseVector2 = inverseVector2.divideBy(4);
        
        // Subtle intensity based on size (well-fed predator is slightly more visible)
        var sizeRatio = this.currentSize / this.baseSize;
        var intensity = 0.3 + (sizeRatio - 1) * 0.2; // Subtle intensity increase when fed
        
        ctx.beginPath();
        ctx.moveTo(this.position.x, this.position.y);
        ctx.lineTo(this.position.x + inverseVector1.x, this.position.y + inverseVector1.y);
        ctx.lineTo(this.position.x + directionVector.x, this.position.y + directionVector.y);
        ctx.lineTo(this.position.x + inverseVector2.x, this.position.y + inverseVector2.y);
        ctx.lineTo(this.position.x, this.position.y);
        
        // Subtle but distinguishable dark red coloring that intensifies when fed
        ctx.strokeStyle = 'rgba(80, 30, 30, ' + (0.7 + intensity * 0.3) + ')';
        ctx.lineWidth = 1;
        ctx.stroke();
        ctx.fillStyle = 'rgba(120, 40, 40, ' + (0.4 + intensity * 0.2) + ')';
        ctx.fill();
        
        // Add a subtle inner highlight that scales with size
        ctx.beginPath();
        ctx.arc(this.position.x, this.position.y, Math.max(2, this.currentSize * 0.15), 0, 2 * Math.PI);
        ctx.fillStyle = 'rgba(140, 60, 60, ' + (0.6 + intensity * 0.2) + ')';
        ctx.fill();
    }
};

// The page boot gate (window.__predatorReady) is owned by js/predator_cheap.js,
// which loads value_net.json before boids.js starts the simulation — so the cheap
// policy drives the predator from frame 1.

/* ===== END VERBATIM js/predator.js ===== */
/* ===== BEGIN VERBATIM js/predator_cheap.js (sha256 a706d6640bdfbde3a0a614471210b34c7f420aa79b083a00a4b7204482ee5421) ===== */
// Cheap ballistic predator policy — the SHIPPED production patrol policy.
//
// Distilled from the receding-horizon planner "teacher" (dev/planner_probe.py).
// Every D=16 frames it picks a patrol target by: generate 16 candidates (E3D
// patrol + 15 nearest-boid lead-adjusted intercepts), rank them by a cheap 2-body
// ballistic catchability sim, roll the K_roll=4 most-catchable candidates Hs=90
// frames through a faithful flat copy of the flock, and argmax (rolled catches +
// value-net terminal bootstrap) vs the other candidates' value-net prior. Then
// each frame it steers with the SAME analytic chase/seek as the old CHASE branch.
//
// This recovers ~90% of the receding-horizon planner's catch rate at ~1/4 its
// rollout cost (sim_torch: K4/Hs90/D16 = 16.88 vs planner 18.75; the deep rollout
// lets the committed target hold for D=16 frames). Cheap enough to run
// SYNCHRONOUSLY on the main thread — no Web Worker, no staleness.
//
// The page boot gate (window.__predatorReady) waits on the value-net load before
// boids.js starts the sim, so this policy drives the predator from frame 1.
//
// The flat rollout (fastMag, grid, accumulateFlock, updateBoid, predatorStepFlat,
// rolloutFlatState) is the byte-identical mirror of boid.js + predator.js; the
// scoring (cp_*) lives in cheap_planner.js. Both are verified against the GPU sim
// (dev/test_cheap_parity.js < 1e-6; dev/eval_cheap_production.js end-to-end).
// Constants come from boid.js + predator.js.
'use strict';

(function () {
    var FRAME_MS = 12, FEED_COOLDOWN = 100, GROWTH = 1.2, DECAY = 0.002;
    var BASE_SIZE = PREDATOR_SIZE, MAX_SIZE = BASE_SIZE * 1.8, CATCH_FACTOR = 0.7;
    var SEP_MULT = 2, COH_MULT = 1, ALIGN_MULT = 1;
    var LEAD_SCALE = EVOLVED_PATROL.lead_scale, LEAD_MAX = EVOLVED_PATROL.lead_max;
    var cfg = { K: 16, K_roll: 4, Hs: 90, D: 16, POLICY_R: 80, W: 1680, Hc: 1680 };

    function fastMag(x, y) {
        var ax = x < 0 ? -x : x, ay = y < 0 ? -y : y;
        return (ax > ay ? ax : ay) * 0.96 + (ax < ay ? ax : ay) * 0.398;
    }

    // ---- flat scratch sim + uniform spatial hash (verbatim from the worker) ----
    var _px, _py, _vx, _vy, _ax, _ay, _alive, _cap = 0;
    function ensureCap(n) {
        if (n <= _cap) return;
        _px = new Float64Array(n); _py = new Float64Array(n);
        _vx = new Float64Array(n); _vy = new Float64Array(n);
        _ax = new Float64Array(n); _ay = new Float64Array(n);
        _alive = new Uint8Array(n); _cap = n;
    }
    var GCELL = NEIGHBOR_DISTANCE, GOFF = 120;
    var g_ncx = 0, g_ncy = 0, g_ncells = 0;
    var g_head, g_next, g_prev, g_cellOf, g_ccap = 0, g_gcap = 0;
    function gridConfig() {
        g_ncx = ((cfg.W + 2 * GOFF) / GCELL | 0) + 2;
        g_ncy = ((cfg.Hc + 2 * GOFF) / GCELL | 0) + 2;
        g_ncells = g_ncx * g_ncy;
        if (g_ncells > g_ccap) { g_head = new Int32Array(g_ncells); g_ccap = g_ncells; }
    }
    function gridEnsure(n) {
        if (n > g_gcap) { g_next = new Int32Array(n); g_prev = new Int32Array(n); g_cellOf = new Int32Array(n); g_gcap = n; }
    }
    function cellIdx(x, y) {
        var cx = (x + GOFF) / GCELL | 0; if (cx < 0) cx = 0; else if (cx >= g_ncx) cx = g_ncx - 1;
        var cy = (y + GOFF) / GCELL | 0; if (cy < 0) cy = 0; else if (cy >= g_ncy) cy = g_ncy - 1;
        return cy * g_ncx + cx;
    }
    function gridReset() { g_head.fill(-1, 0, g_ncells); }
    function gridInsert(i, x, y) {
        var c = cellIdx(x, y); g_cellOf[i] = c; g_prev[i] = -1;
        var h = g_head[c]; g_next[i] = h; if (h >= 0) g_prev[h] = i; g_head[c] = i;
    }
    function gridRemove(i) {
        var c = g_cellOf[i]; if (c < 0) return;
        var pr = g_prev[i], nx = g_next[i];
        if (pr >= 0) g_next[pr] = nx; else g_head[c] = nx;
        if (nx >= 0) g_prev[nx] = pr;
        g_cellOf[i] = -1;
    }
    function gridMove(i, x, y) {
        var nc = cellIdx(x, y); if (nc === g_cellOf[i]) return;
        gridRemove(i);
        g_cellOf[i] = nc; g_prev[i] = -1;
        var h = g_head[nc]; g_next[i] = h; if (h >= 0) g_prev[h] = i; g_head[nc] = i;
    }
    function gridBuild(px, py, alive, n) {
        gridConfig(); gridEnsure(n); gridReset();
        for (var i = 0; i < n; i++) if (alive[i]) gridInsert(i, px[i], py[i]);
    }

    function accumulateFlock(px, py, vx, vy, ax, ay, alive, i, n, predX, predY) {
        var pix = px[i], piy = py[i];
        var cx = 0, cy = 0, cn = 0, sx = 0, sy = 0, sn = 0, alx = 0, aly = 0, an = 0;
        var ci = g_cellOf[i], cyi = (ci / g_ncx) | 0, cxi = ci - cyi * g_ncx;
        var gylo = cyi > 0 ? cyi - 1 : 0, gyhi = cyi < g_ncy - 1 ? cyi + 1 : g_ncy - 1;
        var gxlo = cxi > 0 ? cxi - 1 : 0, gxhi = cxi < g_ncx - 1 ? cxi + 1 : g_ncx - 1;
        for (var gy = gylo; gy <= gyhi; gy++) {
            var rowbase = gy * g_ncx;
            for (var gx = gxlo; gx <= gxhi; gx++) {
                for (var j = g_head[rowbase + gx]; j >= 0; j = g_next[j]) {
                    if (j === i) continue;
                    var rx = px[j] - pix, ry = py[j] - piy;
                    var dist = Math.sqrt(rx * rx + ry * ry) + EPSILON;
                    if (dist <= NEIGHBOR_DISTANCE) { cx += px[j]; cy += py[j]; cn++; }
                    if (dist > 0 && dist < DESIRED_SEPARATION) {
                        var ddx = -rx, ddy = -ry;
                        var m = Math.sqrt(ddx * ddx + ddy * ddy);
                        if (m > 0) { ddx /= m; ddy /= m; }
                        ddx /= dist; ddy /= dist;
                        sx += ddx; sy += ddy; sn++;
                    }
                    if (dist > 0 && dist < NEIGHBOR_DISTANCE) { alx += vx[j]; aly += vy[j]; an++; }
                }
            }
        }
        var vxi = vx[i], vyi = vy[i], fm, s;
        var cohx = 0, cohy = 0;
        if (cn > 0) {
            var dx = cx / cn - pix, dy = cy / cn - piy;
            fm = fastMag(dx, dy); if (fm > 0) { s = MAX_SPEED / fm; dx *= s; dy *= s; }
            dx -= vxi; dy -= vyi;
            fm = fastMag(dx, dy); if (fm > MAX_FORCE) { s = MAX_FORCE / fm; dx *= s; dy *= s; }
            cohx = dx; cohy = dy;
        }
        var sepx = 0, sepy = 0;
        if (sn > 0) { sepx = sx / sn; sepy = sy / sn; }
        fm = fastMag(sepx, sepy);
        if (fm > 0) {
            s = MAX_SPEED / fm; sepx *= s; sepy *= s;
            sepx -= vxi; sepy -= vyi;
            fm = fastMag(sepx, sepy); if (fm > MAX_FORCE) { s = MAX_FORCE / fm; sepx *= s; sepy *= s; }
        }
        var algx = 0, algy = 0;
        if (an > 0) {
            var avx = alx / an, avy = aly / an;
            fm = fastMag(avx, avy); if (fm > 0) { s = MAX_SPEED / fm; avx *= s; avy *= s; }
            avx -= vxi; avy -= vyi;
            fm = fastMag(avx, avy); if (fm > MAX_FORCE) { s = MAX_FORCE / fm; avx *= s; avy *= s; }
            algx = avx; algy = avy;
        }
        sepx *= SEP_MULT; sepy *= SEP_MULT;
        cohx *= COH_MULT; cohy *= COH_MULT;
        algx *= ALIGN_MULT; algy *= ALIGN_MULT;
        ax[i] += cohx; ay[i] += cohy;
        ax[i] += sepx; ay[i] += sepy;
        ax[i] += algx; ay[i] += algy;
        var qx = pix - predX, qy = piy - predY;
        var pdist = Math.sqrt(qx * qx + qy * qy) + EPSILON;
        if (pdist > 0 && pdist < PREDATOR_RANGE) {
            fm = fastMag(qx, qy); if (fm > 0) { qx /= fm; qy /= fm; }
            var str = (PREDATOR_RANGE - pdist) / PREDATOR_RANGE * PREDATOR_TURN_FACTOR;
            qx *= str; qy *= str;
            var lim = MAX_FORCE * 1.5;
            fm = fastMag(qx, qy); if (fm > lim) { s = lim / fm; qx *= s; qy *= s; }
            ax[i] += qx; ay[i] += qy;
        }
    }

    function updateBoid(px, py, vx, vy, ax, ay, i) {
        vx[i] += ax[i]; vy[i] += ay[i];
        var fm = fastMag(vx[i], vy[i]);
        if (fm > MAX_SPEED) { var s = MAX_SPEED / fm; vx[i] *= s; vy[i] *= s; }
        px[i] += vx[i]; py[i] += vy[i];
        var B = BORDER_OFFSET;
        if (px[i] > cfg.W + B) px[i] = -B;
        if (px[i] < -B) px[i] = cfg.W + B;
        if (py[i] > cfg.Hc + B) py[i] = -B;
        if (py[i] < -B) py[i] = cfg.Hc + B;
        ax[i] = 0; ay[i] = 0;
    }

    function predatorStepFlat(px, py, alive, n, p, tx, ty) {
        var bestD2 = Infinity, nx = 0, ny = 0;
        for (var i = 0; i < n; i++) {
            if (!alive[i]) continue;
            var dx = px[i] - p.x, dy = py[i] - p.y;
            var d2 = dx * dx + dy * dy;
            if (d2 < bestD2) { bestD2 = d2; nx = dx; ny = dy; }
        }
        var desx, desy;
        if (bestD2 < cfg.POLICY_R * cfg.POLICY_R) { desx = nx; desy = ny; }
        else { desx = tx - p.x; desy = ty - p.y; }
        var fm = fastMag(desx, desy);
        if (fm > 0) { var sc = PREDATOR_MAX_SPEED / fm; desx *= sc; desy *= sc; }
        var stx = desx - p.vx, sty = desy - p.vy;
        fm = fastMag(stx, sty);
        if (fm > PREDATOR_MAX_FORCE) { var sc2 = PREDATOR_MAX_FORCE / fm; stx *= sc2; sty *= sc2; }
        p.vx += stx; p.vy += sty;
        fm = fastMag(p.vx, p.vy);
        if (fm > PREDATOR_MAX_SPEED) { var sc3 = PREDATOR_MAX_SPEED / fm; p.vx *= sc3; p.vy *= sc3; }
        p.x += p.vx; p.y += p.vy;
        var B = 20;
        if (p.x > cfg.W + B) p.x = -B; if (p.x < -B) p.x = cfg.W + B;
        if (p.y > cfg.Hc + B) p.y = -B; if (p.y < -B) p.y = cfg.Hc + B;
    }

    function snapAlive(px, py, vx, vy, alive, n, p, size, lastFeed, now) {
        var bx = [], by = [], bvx = [], bvy = [];
        for (var i = 0; i < n; i++) {
            if (!alive[i]) continue;
            bx.push(px[i]); by.push(py[i]); bvx.push(vx[i]); bvy.push(vy[i]);
        }
        return { bx: bx, by: by, bvx: bvx, bvy: bvy, px: p.x, py: p.y, pvx: p.vx, pvy: p.vy,
            psize: size, lastFeed: lastFeed, nowMs: now };
    }

    // Roll one target H frames; return catches + terminal snapshot (for the bootstrap).
    function rolloutFlatState(s, tx, ty, H) {
        var n = s.bx.length;
        ensureCap(n);
        for (var i = 0; i < n; i++) {
            _px[i] = s.bx[i]; _py[i] = s.by[i]; _vx[i] = s.bvx[i]; _vy[i] = s.bvy[i];
            _ax[i] = 0; _ay[i] = 0; _alive[i] = 1;
        }
        gridBuild(_px, _py, _alive, n);
        var p = { x: s.px, y: s.py, vx: s.pvx, vy: s.pvy };
        var size = s.psize, lastFeed = (s.lastFeed != null ? s.lastFeed : -1e9), now = s.nowMs || 0, catches = 0;
        for (var f = 0; f < H; f++) {
            for (i = 0; i < n; i++) if (_alive[i]) accumulateFlock(_px, _py, _vx, _vy, _ax, _ay, _alive, i, n, p.x, p.y);
            for (i = 0; i < n; i++) if (_alive[i]) { accumulateFlock(_px, _py, _vx, _vy, _ax, _ay, _alive, i, n, p.x, p.y); updateBoid(_px, _py, _vx, _vy, _ax, _ay, i); gridMove(i, _px[i], _py[i]); }
            predatorStepFlat(_px, _py, _alive, n, p, tx, ty);
            var cr = size * CATCH_FACTOR;
            for (i = 0; i < n; i++) {
                if (!_alive[i]) continue;
                var ex = p.x - _px[i], ey = p.y - _py[i];
                if (Math.sqrt(ex * ex + ey * ey) < cr) {
                    size = Math.min(size + GROWTH, MAX_SIZE); lastFeed = now; _alive[i] = 0; gridRemove(i); catches++; break;
                }
            }
            now += FRAME_MS;
        }
        return { catches: catches, term: snapAlive(_px, _py, _vx, _vy, _alive, n, p, size, lastFeed, now) };
    }

    // 16 candidate targets: cand0 = E3D evolved patrol; cand1..15 = nearest live
    // boids lead-adjusted. Identical to the planner worker's candidates().
    function candidates(s) {
        var n = s.bx.length, i;
        var lite = new Array(n);
        for (i = 0; i < n; i++) lite[i] = { position: { x: s.bx[i], y: s.by[i] }, velocity: { x: s.bvx[i], y: s.bvy[i] } };
        var e3d = computeEvolvedTarget({ x: s.px, y: s.py }, lite, EVOLVED_PATROL, null) || { x: s.px, y: s.py };
        var cands = [{ x: e3d.x, y: e3d.y }];
        var order = [];
        for (i = 0; i < n; i++) { var dx = s.bx[i] - s.px, dy = s.by[i] - s.py; order.push([dx * dx + dy * dy, i]); }
        order.sort(function (a, b) { return a[0] - b[0]; });
        for (var k = 0; k < cfg.K - 1; k++) {
            if (k < order.length) {
                var j = order[k][1];
                var bx = s.bx[j], by = s.by[j], bvx = s.bvx[j], bvy = s.bvy[j];
                var ddx = bx - s.px, ddy = by - s.py;
                var dcent = Math.sqrt(ddx * ddx + ddy * ddy);
                var lead = Math.min(Math.max(dcent / PREDATOR_MAX_SPEED * LEAD_SCALE, 0), LEAD_MAX);
                cands.push({ x: bx + lead * bvx, y: by + lead * bvy });
            } else {
                cands.push({ x: e3d.x, y: e3d.y });
            }
        }
        return cands;
    }

    // The kr=1 ballistic decision. NET = value_net.json (loaded below). vizModel
    // mirrors the value net for activation_viz.js (the "predator's brain").
    var NET = null, vizModel = null;
    function planCheap(s) {
        var cands = candidates(s);
        var st = { px: s.px, py: s.py, pvx: s.pvx, pvy: s.pvy, psize: s.psize,
            bx: s.bx, by: s.by, bvx: s.bvx, bvy: s.bvy, nAlive: s.bx.length };
        var fr = cp_features(st, cands, PREDATOR_MAX_SPEED, PREDATOR_MAX_FORCE);
        var vprior = cp_value(NET, fr.feat, fr.ctx);
        // Roll the top-K_roll candidates by ballistic pscore (caught - tCatchNorm);
        // ties (the common case for the slow predator) break by lowest index, so
        // this rolls the E3D patrol + the nearest live boids. Each rolled candidate
        // is scored by (rollout catches + value-net terminal bootstrap); the rest
        // keep their value-net prior. argmax commits.
        var pidx = []; for (var pk = 0; pk < cands.length; pk++) pidx.push(pk);
        pidx.sort(function (a, b) { var pa = fr.feat[a][18] - fr.feat[a][16], pb = fr.feat[b][18] - fr.feat[b][16]; return (pb - pa) || (a - b); });
        var score = vprior.slice();
        for (var rk = 0; rk < cfg.K_roll && rk < pidx.length; rk++) {
            var ci = pidx[rk];
            var rr = rolloutFlatState(s, cands[ci].x, cands[ci].y, cfg.Hs);
            var t = rr.term;
            var tcands = candidates(t);
            var tst = { px: t.px, py: t.py, pvx: t.pvx, pvy: t.pvy, psize: t.psize,
                bx: t.bx, by: t.by, bvx: t.bvx, bvy: t.bvy, nAlive: t.bx.length };
            var tfr = cp_features(tst, tcands, PREDATOR_MAX_SPEED, PREDATOR_MAX_FORCE);
            var tv = cp_value(NET, tfr.feat, tfr.ctx);
            var boot = -Infinity; for (var j = 0; j < tv.length; j++) if (tv[j] > boot) boot = tv[j];
            score[ci] = rr.catches + boot;
        }
        var bi = 0, bs = -Infinity;
        for (var k = 0; k < score.length; k++) if (score[k] > bs) { bs = score[k]; bi = k; }
        // Record the chosen candidate's value-net forward for the brain viz.
        if (vizModel) cp_value_viz(NET, fr.feat[bi], fr.ctx, vizModel);
        return { x: cands[bi].x, y: cands[bi].y };
    }

    // ---- per-frame driver ----
    var target = null, frame = 0, configured = false;

    function configure(sim) {
        cfg.W = sim.canvasWidth; cfg.Hc = sim.canvasHeight;
        configured = true;
    }

    function snapshot(pred, boids) {
        var n = boids.length;
        var bx = new Array(n), by = new Array(n), bvx = new Array(n), bvy = new Array(n);
        for (var i = 0; i < n; i++) {
            bx[i] = boids[i].position.x; by[i] = boids[i].position.y;
            bvx[i] = boids[i].velocity.x; bvy[i] = boids[i].velocity.y;
        }
        return { bx: bx, by: by, bvx: bvx, bvy: bvy,
            px: pred.position.x, py: pred.position.y, pvx: pred.velocity.x, pvy: pred.velocity.y,
            psize: pred.currentSize, lastFeed: pred.lastFeedTime, nowMs: simNow() };
    }

    // Chase nearest within POLICY_R, else seek the committed target — the same
    // analytic step as the production CHASE branch + the worker predatorStep.
    function steer(pred, boids) {
        var px = pred.position.x, py = pred.position.y;
        var bestD2 = Infinity, nx = 0, ny = 0;
        for (var i = 0, n = boids.length; i < n; i++) {
            var dx = boids[i].position.x - px, dy = boids[i].position.y - py;
            var d2 = dx * dx + dy * dy;
            if (d2 < bestD2) { bestD2 = d2; nx = dx; ny = dy; }
        }
        var desired;
        if (bestD2 < cfg.POLICY_R * cfg.POLICY_R) desired = new Vector(nx, ny);
        else if (target) desired = new Vector(target.x - px, target.y - py);
        else desired = new Vector(nx, ny);
        desired.iFastSetMagnitude(PREDATOR_MAX_SPEED);
        var s = desired.subtract(pred.velocity);
        s.iFastLimit(PREDATOR_MAX_FORCE);
        return s;
    }

    // ENDGAME INTERCEPTOR — used for the last <=5 boids. A lone survivor has no
    // flockmates, so it flies a near-straight line and the lookahead above degrades
    // into a tail-chase the 2.4x-slower predator can never win (it gets stuck and
    // never clears the last boid 12-18% of the time on big screens). The slow
    // predator's one structural edge is the torus WRAP: scan the target's straight
    // track at single-frame resolution for the EARLIEST point the predator can reach
    // in time (min-image at the boid period W+20 — the short backward-wrap puts the
    // predator AHEAD of the boid for a head-on catch, closing up to 8.5/frame vs the
    // -3.5 tail-chase deficit) and re-aim there every frame. ~6x faster + 100%
    // reliable on the last boid. (Occam: an earlier "freeze the aim and commit"
    // variant was strictly worse — re-aiming every frame is both simpler and better.
    // Validated 4 ways: JS lab, real eval harness, an independent audit, and a
    // 4096-env GPU sweep.)
    var egBoid = null;
    function intercept(pred, boids) {
        var px = pred.position.x, py = pred.position.y, sM = PREDATOR_MAX_SPEED;
        var PX = cfg.W + 2 * BORDER_OFFSET, PY = cfg.Hc + 2 * BORDER_OFFSET, TMAX = 1400;
        function wx(d) { return d - PX * Math.round(d / PX); }
        function wy(d) { return d - PY * Math.round(d / PY); }
        // earliest frame t at which the predator can stand where boid B will be
        function scan(B) {
            var bx = B.position.x, by = B.position.y, bvx = B.velocity.x, bvy = B.velocity.y;
            for (var t = 0; t <= TMAX; t++) {
                var ddx = wx(bx + bvx * t - px), ddy = wy(by + bvy * t - py);
                if (Math.sqrt(ddx * ddx + ddy * ddy) <= sM * t) return { ax: ddx, ay: ddy, t: t };
            }
            return null;
        }
        // commit to one target until it is caught (don't dither among the last few);
        // pick the soonest-reachable boid, falling back to the nearest if none qualify.
        if (egBoid && boids.indexOf(egBoid) < 0) egBoid = null;
        if (!egBoid) {
            var bestT = Infinity, i;
            for (i = 0; i < boids.length; i++) { var c = scan(boids[i]); if (c && c.t < bestT) { bestT = c.t; egBoid = boids[i]; } }
            if (!egBoid) {
                var nd2 = Infinity;
                for (i = 0; i < boids.length; i++) { var dx = wx(boids[i].position.x - px), dy = wy(boids[i].position.y - py); var d2 = dx * dx + dy * dy; if (d2 < nd2) { nd2 = d2; egBoid = boids[i]; } }
            }
        }
        // aim at the earliest-reachable point (perpendicular cut-off onto its line if none)
        var s = scan(egBoid), aimX, aimY;
        if (s) { aimX = s.ax; aimY = s.ay; }
        else {
            var cdx = wx(egBoid.position.x - px), cdy = wy(egBoid.position.y - py);
            var bs = Math.sqrt(egBoid.velocity.x * egBoid.velocity.x + egBoid.velocity.y * egBoid.velocity.y) || 1e-6;
            var ux = egBoid.velocity.x / bs, uy = egBoid.velocity.y / bs, along = cdx * ux + cdy * uy;
            aimX = cdx - along * ux; aimY = cdy - along * uy;
        }
        var desired = new Vector(aimX, aimY);
        desired.iFastSetMagnitude(sM);
        var st = desired.subtract(pred.velocity);
        st.iFastLimit(PREDATOR_MAX_FORCE);
        return st;
    }

    window.__cheap = {
        force: function (pred, boids) {
            if (boids.length === 0) return new Vector(0, 0);
            if (!configured && pred.simulation) configure(pred.simulation);
            if (boids.length <= 5) return intercept(pred, boids);   // ENDGAME: torus head-on intercept
            if (frame === 0 || frame >= cfg.D) { target = planCheap(snapshot(pred, boids)); frame = 0; }
            frame++;
            return steer(pred, boids);
        }
    };

    // Own the page boot gate: boids.js waits on window.__predatorReady before
    // starting the sim, so the value net is loaded before frame 1.
    if (typeof window !== 'undefined' && typeof fetch !== 'undefined') {
        window.__predatorReady = fetch('js/value_net.json', { cache: 'no-cache' })
            .then(function (r) { if (!r.ok) throw new Error('value_net fetch failed: ' + r.status); return r.json(); })
            .then(function (net) { NET = net; vizModel = cp_viz_model(net); window.__predatorModel = vizModel; });
    }
})();

/* ===== END VERBATIM js/predator_cheap.js ===== */
        return window;       // -> {__cheap, __predatorReady, __predatorModel}
    })();
    var api = {
        force: captured.__cheap.force,   // THE prod closure, no indirection
        ready: captured.__predatorReady, // resolves when the net is parsed
        _inner: captured,                // harness debug surface (transform builds)
    };
    if (REALMODULE) REALMODULE.exports = api;
    if (REALWIN) REALWIN.__exactnn = api;
})(typeof window !== 'undefined' ? window : null,
   typeof module !== 'undefined' ? module : null);
